-- ==================================================
-- database\schema.sql
-- ==================================================
CREATE TABLE departments (
  department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  department_name VARCHAR2(100) NOT NULL,
  location VARCHAR2(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_departments PRIMARY KEY (department_id),
  CONSTRAINT uq_departments_name UNIQUE (department_name)
);

CREATE TABLE patients (
  patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR2(100) NOT NULL,
  last_name VARCHAR2(100) NOT NULL,
  date_of_birth DATE,
  gender VARCHAR2(20),
  phone VARCHAR2(30),
  email VARCHAR2(150),
  address VARCHAR2(300),
  blood_group VARCHAR2(5),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_patients PRIMARY KEY (patient_id)
);

CREATE TABLE doctors (
  doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  department_id NUMBER NOT NULL,
  first_name VARCHAR2(100) NOT NULL,
  last_name VARCHAR2(100) NOT NULL,
  specialization VARCHAR2(120) NOT NULL,
  phone VARCHAR2(30),
  email VARCHAR2(150),
  hire_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_doctors PRIMARY KEY (doctor_id),
  CONSTRAINT fk_doctors_department FOREIGN KEY (department_id)
    REFERENCES departments(department_id)
);

CREATE TABLE rooms (
  room_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  department_id NUMBER,
  room_number VARCHAR2(20) NOT NULL,
  room_type VARCHAR2(50),
  bed_count NUMBER DEFAULT 1 NOT NULL,
  daily_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  status VARCHAR2(30) DEFAULT 'AVAILABLE' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_rooms PRIMARY KEY (room_id),
  CONSTRAINT uq_rooms_number UNIQUE (room_number),
  CONSTRAINT fk_rooms_department FOREIGN KEY (department_id)
    REFERENCES departments(department_id)
);

CREATE TABLE appointments (
  appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  appointment_date DATE NOT NULL,
  reason VARCHAR2(300),
  status VARCHAR2(30) DEFAULT 'SCHEDULED' NOT NULL,
  notes VARCHAR2(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_appointments PRIMARY KEY (appointment_id),
  CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id)
    REFERENCES doctors(doctor_id)
);

CREATE TABLE admissions (
  admission_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  room_id NUMBER NOT NULL,
  admission_date DATE NOT NULL,
  discharge_date DATE,
  diagnosis VARCHAR2(500),
  status VARCHAR2(30) DEFAULT 'ADMITTED' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_admissions PRIMARY KEY (admission_id),
  CONSTRAINT fk_admissions_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_admissions_doctor FOREIGN KEY (doctor_id)
    REFERENCES doctors(doctor_id),
  CONSTRAINT fk_admissions_room FOREIGN KEY (room_id)
    REFERENCES rooms(room_id)
);

CREATE TABLE lab_tests (
  lab_test_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER,
  appointment_id NUMBER,
  test_name VARCHAR2(150) NOT NULL,
  test_date DATE DEFAULT SYSDATE NOT NULL,
  result VARCHAR2(1000),
  status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
  cost NUMBER(10,2) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_lab_tests PRIMARY KEY (lab_test_id),
  CONSTRAINT fk_lab_tests_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_lab_tests_doctor FOREIGN KEY (doctor_id)
    REFERENCES doctors(doctor_id),
  CONSTRAINT fk_lab_tests_appointment FOREIGN KEY (appointment_id)
    REFERENCES appointments(appointment_id)
);

CREATE TABLE bills (
  bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id NUMBER NOT NULL,
  admission_id NUMBER,
  appointment_id NUMBER,
  bill_date DATE DEFAULT SYSDATE NOT NULL,
  consultation_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  room_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  lab_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  medicine_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  total_amount NUMBER(12,2) NOT NULL,
  payment_status VARCHAR2(30) DEFAULT 'UNPAID' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_bills PRIMARY KEY (bill_id),
  CONSTRAINT fk_bills_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_bills_admission FOREIGN KEY (admission_id)
    REFERENCES admissions(admission_id),
  CONSTRAINT fk_bills_appointment FOREIGN KEY (appointment_id)
    REFERENCES appointments(appointment_id)
);

CREATE INDEX idx_doctors_department ON doctors(department_id);
CREATE INDEX idx_rooms_department ON rooms(department_id);
CREATE INDEX idx_appointments_date ON appointments(appointment_date);
CREATE INDEX idx_appointments_patient ON appointments(patient_id);
CREATE INDEX idx_appointments_doctor ON appointments(doctor_id);
CREATE INDEX idx_admissions_patient ON admissions(patient_id);
CREATE INDEX idx_admissions_room ON admissions(room_id);
CREATE INDEX idx_lab_tests_patient ON lab_tests(patient_id);
CREATE INDEX idx_bills_patient ON bills(patient_id);

-- ==================================================
-- database\procedures.sql
-- ==================================================
CREATE OR REPLACE PROCEDURE create_appointment (
  p_patient_id IN appointments.patient_id%TYPE,
  p_doctor_id IN appointments.doctor_id%TYPE,
  p_appointment_date IN appointments.appointment_date%TYPE,
  p_reason IN appointments.reason%TYPE DEFAULT NULL,
  p_notes IN appointments.notes%TYPE DEFAULT NULL,
  p_appointment_id OUT appointments.appointment_id%TYPE
) AS
BEGIN
  INSERT INTO appointments (
    patient_id,
    doctor_id,
    appointment_date,
    reason,
    notes
  ) VALUES (
    p_patient_id,
    p_doctor_id,
    p_appointment_date,
    p_reason,
    p_notes
  )
  RETURNING appointment_id INTO p_appointment_id;
END;
/

CREATE OR REPLACE FUNCTION calculate_total_bill (
  p_patient_id IN patients.patient_id%TYPE
) RETURN NUMBER AS
  v_total_amount NUMBER(12,2);
BEGIN
  SELECT NVL(SUM(total_amount), 0)
  INTO v_total_amount
  FROM bills
  WHERE patient_id = p_patient_id;

  RETURN v_total_amount;
END;
/

CREATE OR REPLACE PROCEDURE generate_bill (
  p_patient_id IN patients.patient_id%TYPE
) AS
  v_admission_id bills.admission_id%TYPE;
  v_appointment_id bills.appointment_id%TYPE;
  v_consultation_charge bills.consultation_charge%TYPE;
  v_room_charge bills.room_charge%TYPE;
  v_lab_charge bills.lab_charge%TYPE;
  v_medicine_charge bills.medicine_charge%TYPE := 0;
BEGIN
  SELECT MAX(admission_id)
  INTO v_admission_id
  FROM admissions
  WHERE patient_id = p_patient_id;

  SELECT MAX(appointment_id)
  INTO v_appointment_id
  FROM appointments
  WHERE patient_id = p_patient_id;

  SELECT COUNT(*) * 800
  INTO v_consultation_charge
  FROM appointments
  WHERE patient_id = p_patient_id;

  SELECT NVL(SUM(
    r.daily_charge * GREATEST(TRUNC(NVL(a.discharge_date, SYSDATE)) - TRUNC(a.admission_date) + 1, 1)
  ), 0)
  INTO v_room_charge
  FROM admissions a
  JOIN rooms r
    ON a.room_id = r.room_id
  WHERE a.patient_id = p_patient_id;

  SELECT NVL(SUM(cost), 0)
  INTO v_lab_charge
  FROM lab_tests
  WHERE patient_id = p_patient_id;

  INSERT INTO bills (
    patient_id,
    admission_id,
    appointment_id,
    bill_date,
    consultation_charge,
    room_charge,
    lab_charge,
    medicine_charge,
    total_amount,
    payment_status
  ) VALUES (
    p_patient_id,
    v_admission_id,
    v_appointment_id,
    SYSDATE,
    v_consultation_charge,
    v_room_charge,
    v_lab_charge,
    v_medicine_charge,
    v_consultation_charge + v_room_charge + v_lab_charge + v_medicine_charge,
    'UNPAID'
  );
END;
/

CREATE OR REPLACE TRIGGER trg_update_bill_after_lab_test
AFTER INSERT ON lab_tests
FOR EACH ROW
DECLARE
  v_rows_updated NUMBER;
BEGIN
  UPDATE bills
  SET lab_charge = lab_charge + NVL(:NEW.cost, 0),
      total_amount = consultation_charge
        + room_charge
        + lab_charge
        + NVL(:NEW.cost, 0)
        + medicine_charge
  WHERE patient_id = :NEW.patient_id
    AND (
      appointment_id = :NEW.appointment_id
      OR :NEW.appointment_id IS NULL
      OR appointment_id IS NULL
    );

  v_rows_updated := SQL%ROWCOUNT;

  IF v_rows_updated = 0 THEN
    INSERT INTO bills (
      patient_id,
      appointment_id,
      bill_date,
      consultation_charge,
      room_charge,
      lab_charge,
      medicine_charge,
      total_amount,
      payment_status
    ) VALUES (
      :NEW.patient_id,
      :NEW.appointment_id,
      SYSDATE,
      0,
      0,
      NVL(:NEW.cost, 0),
      0,
      NVL(:NEW.cost, 0),
      'UNPAID'
    );
  END IF;
END;
/

-- ==================================================
-- database\seed.sql
-- ==================================================
INSERT INTO departments (department_name, location)
VALUES ('Cardiology', 'Block A - Floor 2');

INSERT INTO departments (department_name, location)
VALUES ('Orthopedics', 'Block B - Floor 3');

INSERT INTO patients (
  first_name,
  last_name,
  date_of_birth,
  gender,
  phone,
  email,
  address,
  blood_group
) VALUES (
  'Aarav',
  'Sharma',
  DATE '1992-03-14',
  'Male',
  '9876543210',
  'aarav.sharma@example.com',
  'Mumbai',
  'B+'
);

INSERT INTO patients (
  first_name,
  last_name,
  date_of_birth,
  gender,
  phone,
  email,
  address,
  blood_group
) VALUES (
  'Ananya',
  'Verma',
  DATE '1988-09-21',
  'Female',
  '9876543211',
  'ananya.verma@example.com',
  'Delhi',
  'O+'
);

INSERT INTO patients (
  first_name,
  last_name,
  date_of_birth,
  gender,
  phone,
  email,
  address,
  blood_group
) VALUES (
  'Rohan',
  'Kapoor',
  DATE '1979-12-05',
  'Male',
  '9876543212',
  'rohan.kapoor@example.com',
  'Pune',
  'A+'
);

INSERT INTO patients (
  first_name,
  last_name,
  date_of_birth,
  gender,
  phone,
  email,
  address,
  blood_group
) VALUES (
  'Priya',
  'Nair',
  DATE '1996-06-30',
  'Female',
  '9876543213',
  'priya.nair@example.com',
  'Bengaluru',
  'AB+'
);

INSERT INTO patients (
  first_name,
  last_name,
  date_of_birth,
  gender,
  phone,
  email,
  address,
  blood_group
) VALUES (
  'Kabir',
  'Khan',
  DATE '2001-01-17',
  'Male',
  '9876543214',
  'kabir.khan@example.com',
  'Hyderabad',
  'O-'
);

INSERT INTO doctors (
  department_id,
  first_name,
  last_name,
  specialization,
  phone,
  email,
  hire_date
) VALUES (
  1,
  'Meera',
  'Iyer',
  'Cardiologist',
  '9876500001',
  'meera.iyer@example.com',
  DATE '2020-06-01'
);

INSERT INTO doctors (
  department_id,
  first_name,
  last_name,
  specialization,
  phone,
  email,
  hire_date
) VALUES (
  2,
  'Arjun',
  'Menon',
  'Orthopedic Surgeon',
  '9876500002',
  'arjun.menon@example.com',
  DATE '2019-02-15'
);

INSERT INTO doctors (
  department_id,
  first_name,
  last_name,
  specialization,
  phone,
  email,
  hire_date
) VALUES (
  1,
  'Nisha',
  'Rao',
  'Interventional Cardiologist',
  '9876500003',
  'nisha.rao@example.com',
  DATE '2021-10-10'
);

INSERT INTO rooms (
  department_id,
  room_number,
  room_type,
  bed_count,
  daily_charge,
  status
) VALUES (
  1,
  'A-201',
  'Private',
  1,
  3500,
  'OCCUPIED'
);

INSERT INTO rooms (
  department_id,
  room_number,
  room_type,
  bed_count,
  daily_charge,
  status
) VALUES (
  2,
  'B-301',
  'Semi-Private',
  2,
  2200,
  'OCCUPIED'
);

INSERT INTO rooms (
  department_id,
  room_number,
  room_type,
  bed_count,
  daily_charge,
  status
) VALUES (
  1,
  'A-202',
  'General',
  4,
  1200,
  'AVAILABLE'
);

INSERT INTO appointments (
  patient_id,
  doctor_id,
  appointment_date,
  reason,
  status,
  notes
) VALUES (
  1,
  1,
  SYSDATE + 1,
  'Chest pain consultation',
  'SCHEDULED',
  'Initial consultation'
);

INSERT INTO appointments (
  patient_id,
  doctor_id,
  appointment_date,
  reason,
  status,
  notes
) VALUES (
  2,
  2,
  SYSDATE + 2,
  'Knee pain evaluation',
  'SCHEDULED',
  'Possible ligament strain'
);

INSERT INTO appointments (
  patient_id,
  doctor_id,
  appointment_date,
  reason,
  status,
  notes
) VALUES (
  3,
  3,
  SYSDATE - 1,
  'Follow-up for hypertension',
  'COMPLETED',
  'Medication review completed'
);

INSERT INTO appointments (
  patient_id,
  doctor_id,
  appointment_date,
  reason,
  status,
  notes
) VALUES (
  4,
  1,
  SYSDATE + 3,
  'Routine cardiac screening',
  'SCHEDULED',
  'ECG requested'
);

INSERT INTO appointments (
  patient_id,
  doctor_id,
  appointment_date,
  reason,
  status,
  notes
) VALUES (
  5,
  2,
  SYSDATE,
  'Shoulder injury',
  'IN_PROGRESS',
  'X-ray advised'
);

INSERT INTO admissions (
  patient_id,
  doctor_id,
  room_id,
  admission_date,
  discharge_date,
  diagnosis,
  status
) VALUES (
  1,
  1,
  1,
  SYSDATE,
  NULL,
  'Observation for cardiac symptoms',
  'ADMITTED'
);

INSERT INTO admissions (
  patient_id,
  doctor_id,
  room_id,
  admission_date,
  discharge_date,
  diagnosis,
  status
) VALUES (
  2,
  2,
  2,
  SYSDATE - 2,
  NULL,
  'Knee ligament injury',
  'ADMITTED'
);

INSERT INTO admissions (
  patient_id,
  doctor_id,
  room_id,
  admission_date,
  discharge_date,
  diagnosis,
  status
) VALUES (
  3,
  3,
  3,
  SYSDATE - 8,
  SYSDATE - 4,
  'Hypertension monitoring',
  'DISCHARGED'
);

INSERT INTO bills (
  patient_id,
  admission_id,
  appointment_id,
  bill_date,
  consultation_charge,
  room_charge,
  lab_charge,
  medicine_charge,
  total_amount,
  payment_status
) VALUES (
  1,
  1,
  1,
  SYSDATE,
  800,
  3500,
  0,
  450,
  4750,
  'UNPAID'
);

INSERT INTO bills (
  patient_id,
  admission_id,
  appointment_id,
  bill_date,
  consultation_charge,
  room_charge,
  lab_charge,
  medicine_charge,
  total_amount,
  payment_status
) VALUES (
  2,
  2,
  2,
  SYSDATE,
  700,
  4400,
  0,
  900,
  6000,
  'PARTIALLY_PAID'
);

INSERT INTO bills (
  patient_id,
  admission_id,
  appointment_id,
  bill_date,
  consultation_charge,
  room_charge,
  lab_charge,
  medicine_charge,
  total_amount,
  payment_status
) VALUES (
  3,
  3,
  3,
  SYSDATE - 4,
  900,
  4800,
  0,
  1200,
  6900,
  'PAID'
);

INSERT INTO lab_tests (
  patient_id,
  doctor_id,
  appointment_id,
  test_name,
  test_date,
  result,
  status,
  cost
) VALUES (
  1,
  1,
  1,
  'Complete Blood Count',
  SYSDATE,
  NULL,
  'PENDING',
  600
);

INSERT INTO lab_tests (
  patient_id,
  doctor_id,
  appointment_id,
  test_name,
  test_date,
  result,
  status,
  cost
) VALUES (
  3,
  3,
  3,
  'Lipid Profile',
  SYSDATE - 1,
  'LDL slightly elevated',
  'COMPLETED',
  950
);

INSERT INTO lab_tests (
  patient_id,
  doctor_id,
  appointment_id,
  test_name,
  test_date,
  result,
  status,
  cost
) VALUES (
  5,
  2,
  5,
  'Shoulder X-Ray',
  SYSDATE,
  NULL,
  'PENDING',
  1200
);

COMMIT;

-- ==================================================
-- database\queries.sql
-- ==================================================
SELECT
  a.appointment_id,
  p.patient_id,
  p.first_name || ' ' || p.last_name AS patient_name,
  d.doctor_id,
  d.first_name || ' ' || d.last_name AS doctor_name,
  dept.department_name,
  a.appointment_date,
  a.reason,
  a.status
FROM appointments a
JOIN patients p
  ON a.patient_id = p.patient_id
JOIN doctors d
  ON a.doctor_id = d.doctor_id
JOIN departments dept
  ON d.department_id = dept.department_id
ORDER BY a.appointment_date;

SELECT
  p.patient_id,
  p.first_name || ' ' || p.last_name AS patient_name,
  SUM(b.total_amount) AS total_billing
FROM patients p
JOIN bills b
  ON p.patient_id = b.patient_id
GROUP BY
  p.patient_id,
  p.first_name,
  p.last_name
ORDER BY total_billing DESC;

SELECT
  p.patient_id,
  p.first_name || ' ' || p.last_name AS patient_name,
  b.bill_id,
  b.total_amount,
  b.payment_status
FROM patients p
JOIN bills b
  ON p.patient_id = b.patient_id
WHERE b.total_amount = (
  SELECT MAX(total_amount)
  FROM bills
);

