CREATE TABLE departments (
  department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  department_name VARCHAR2(100) NOT NULL,
  location VARCHAR2(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_departments PRIMARY KEY (department_id),
  CONSTRAINT uq_departments_name UNIQUE (department_name)
);

CREATE TABLE patients (
  patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR2(100) NOT NULL,
  last_name VARCHAR2(100) NOT NULL,
  date_of_birth DATE,
  gender VARCHAR2(20),
  phone VARCHAR2(30),
  email VARCHAR2(150),
  address VARCHAR2(300),
  blood_group VARCHAR2(5),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_patients PRIMARY KEY (patient_id)
);

CREATE TABLE doctors (
  doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  department_id NUMBER NOT NULL,
  first_name VARCHAR2(100) NOT NULL,
  last_name VARCHAR2(100) NOT NULL,
  specialization VARCHAR2(120) NOT NULL,
  phone VARCHAR2(30),
  email VARCHAR2(150),
  hire_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_doctors PRIMARY KEY (doctor_id),
  CONSTRAINT fk_doctors_department FOREIGN KEY (department_id)
    REFERENCES departments(department_id)
);

CREATE TABLE rooms (
  room_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  department_id NUMBER,
  room_number VARCHAR2(20) NOT NULL,
  room_type VARCHAR2(50),
  bed_count NUMBER DEFAULT 1 NOT NULL,
  daily_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  status VARCHAR2(30) DEFAULT 'AVAILABLE' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_rooms PRIMARY KEY (room_id),
  CONSTRAINT uq_rooms_number UNIQUE (room_number),
  CONSTRAINT fk_rooms_department FOREIGN KEY (department_id)
    REFERENCES departments(department_id)
);

CREATE TABLE appointments (
  appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  appointment_date DATE NOT NULL,
  reason VARCHAR2(300),
  status VARCHAR2(30) DEFAULT 'SCHEDULED' NOT NULL,
  notes VARCHAR2(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_appointments PRIMARY KEY (appointment_id),
  CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id)
    REFERENCES doctors(doctor_id)
);

CREATE TABLE admissions (
  admission_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  room_id NUMBER NOT NULL,
  admission_date DATE NOT NULL,
  discharge_date DATE,
  diagnosis VARCHAR2(500),
  status VARCHAR2(30) DEFAULT 'ADMITTED' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_admissions PRIMARY KEY (admission_id),
  CONSTRAINT fk_admissions_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_admissions_doctor FOREIGN KEY (doctor_id)
    REFERENCES doctors(doctor_id),
  CONSTRAINT fk_admissions_room FOREIGN KEY (room_id)
    REFERENCES rooms(room_id)
);

CREATE TABLE lab_tests (
  lab_test_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER,
  appointment_id NUMBER,
  test_name VARCHAR2(150) NOT NULL,
  test_date DATE DEFAULT SYSDATE NOT NULL,
  result VARCHAR2(1000),
  status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
  cost NUMBER(10,2) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_lab_tests PRIMARY KEY (lab_test_id),
  CONSTRAINT fk_lab_tests_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_lab_tests_doctor FOREIGN KEY (doctor_id)
    REFERENCES doctors(doctor_id),
  CONSTRAINT fk_lab_tests_appointment FOREIGN KEY (appointment_id)
    REFERENCES appointments(appointment_id)
);

CREATE TABLE bills (
  bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id NUMBER NOT NULL,
  admission_id NUMBER,
  appointment_id NUMBER,
  bill_date DATE DEFAULT SYSDATE NOT NULL,
  consultation_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  room_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  lab_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  medicine_charge NUMBER(10,2) DEFAULT 0 NOT NULL,
  total_amount NUMBER(12,2) NOT NULL,
  payment_status VARCHAR2(30) DEFAULT 'UNPAID' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_bills PRIMARY KEY (bill_id),
  CONSTRAINT fk_bills_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_bills_admission FOREIGN KEY (admission_id)
    REFERENCES admissions(admission_id),
  CONSTRAINT fk_bills_appointment FOREIGN KEY (appointment_id)
    REFERENCES appointments(appointment_id)
);

CREATE INDEX idx_doctors_department ON doctors(department_id);
CREATE INDEX idx_rooms_department ON rooms(department_id);
CREATE INDEX idx_appointments_date ON appointments(appointment_date);
CREATE INDEX idx_appointments_patient ON appointments(patient_id);
CREATE INDEX idx_appointments_doctor ON appointments(doctor_id);
CREATE INDEX idx_admissions_patient ON admissions(patient_id);
CREATE INDEX idx_admissions_room ON admissions(room_id);
CREATE INDEX idx_lab_tests_patient ON lab_tests(patient_id);
CREATE INDEX idx_bills_patient ON bills(patient_id);
